<?php

namespace App\Utils;

class BibleBookShortUtils {

    private static $englichShorts = array(
    "Genesis"=>"Gen.", 
        "Exodus"=>"Ex.", 
        "Leviticus"=>"Lev.",
        "Numbers"=>"Num.",
        "Deuteronomy"=>"Deut.",
        "Joshua"=>"Josh.",
        "Judges"=>"Judg.",
        "Ruth"=>"Ruth",
        "1 Samuel"=>"1Sam.",
        "2 Samuel"=>"2Sam.",
        "1 Kings"=>"1Kings",
        "2 Kings"=>"2Kings",
        "1 Chronicles"=>"1Chron.",
        "2 Chronicles"=>"2Chron.",
        "Ezra"=>"Ezra",
        "Nehemiah"=>"Neh.",
        "Esther"=>"Est.",
        "Job"=>"Job",
        "Psalms"=>"Ps.",
        "Proverbs"=>"Prov.",
        "Ecclesiastes"=>"Eccles.",
        "Song of Songs"=>"Song",
        "Isaiah"=>"Isa.",
        "Jeremiah"=>"Jer.",
        "Lamentations"=>"Lam.",
        "Ezekiel"=>"Ezek.",
        "Daniel"=>"Dan.",
        "Hosea"=>"Hos.",
        "Joel"=>"Joel",
        "Amos"=>"Amos",
        "Obadiah"=>"Obad.",
        "Jonah"=>"Jonah",
        "Micah"=>"Mic.",
        "Nahum"=>"Nah.",
        "Habakkuk"=>"Hab.",
        "Zephaniah"=>"Zeph.",
        "Haggai"=>"Hag.",
        "Zechariah"=>"Zech.",
        "Malachi"=>"Mal.",

        "Matthew"=>"Matt.",
        "Mark"=>"Mark",
        "Luke"=>"Luke",
        "John"=>"John",
        "Acts"=>"Acts",
        "Romans"=>"Rom.",
        "1 Corinthians"=>"1Cor.",
        "2 Corinthians"=>"2Cor.",
        "Galatians"=>"Gal.",
        "Ephesians"=>"Eph.",
        "Philippians"=>"Phil.",
        "Colossians"=>"Col.",
        "1 Thessalonians"=>"1Thess.",
        "2 Thessalonians"=>"2Thess.",
        "1 Timothy"=>"1Tim.",
        "2 Timothy"=>"2Tim.",
        "Titus"=>"Titus",
        "Philemon"=>"Philem.",
        "Hebrews"=>"Heb.",
        "James"=>"James",
        "1 Peter"=>"1Pet.",
        "2 Peter"=>"2Pet.",
        "1 John"=>"1Joh.",
        "2 John"=>"2Joh.",
        "3 John"=>"3Joh.",
        "Jude"=>"Jude",
        "Revelation"=>"Rev.",
    );

    private static $frenchShorts = array(
        "1" =>["name" => "Genèse", "short" => "Gn."], 
        "2"=>["name" => "Exode", "short" =>"Ex."],  
        "3"=>["name" => "Lévitique", "short" => "Lv."],
        "4"=>["name" => "Nombres", "short" => "Nb."],
        "5"=>["name" => "Deutéronome", "short" => "Dt."],
        "6"=>["name" => "Josué", "short" => "Js."],
        "7"=>["name" => "Juges", "short" => "Jg."],
        "8"=>["name" => "Ruth", "short" => "Rt."],
        "9"=>["name" => "1 Samuel", "short" => "1Sam."],
        "10"=>["name" => "2 Samuel", "short" => "2Sam."],
        "11"=>["name" => "1 Rois", "short" => "1Ro"],
        "12"=>["name" => "2 Rois", "short" => "2Ro"],
        "13"=>["name" => "1 Chroniques", "short" => "1Ch."],
        "14"=>["name" => "2 Chroniques", "short" => "2Ch."],
        "15"=>["name" => "Esdras", "short" => "Esd."],
        "16"=>["name" => "Néhémie", "short" => "Ne."],
        "17"=>["name" => "Esther", "short" => "Est."],
        "18"=>["name" => "Job", "short" => "Jb."],
        "19"=>["name" => "Psalms", "short" => "Ps."],
        "20"=>["name" => "Proverbes", "short" => "Pr."],
        "21"=>["name" => "Ecclésiastes", "short" => "Ec."],
        "22"=>["name" => "Cantique", "short" => "Cant."],
        "23"=>["name" => "Ésaïe", "short" => "Es."],
        "24"=>["name" => "Jérémie", "short" => "Jer."],
        "25"=>["name" => "Lamentations", "short" => "Lam."],
        "26"=>["name" => "Ézékiel", "short" => "Ezek."],
        "27"=>["name" => "Daniel", "short" => "Dan."],
        "28"=>["name" => "Osée", "short" => "Hos."],
        "29"=>["name" => "Joël", "short" => "Jl."],
        "30"=>["name" => "Amos", "short" => "Am."],
        "31"=>["name" => "Abdias", "short" => "Ab."],
        "32"=>["name" => "Jonas", "short" => "Jon."],
        "33"=>["name" => "Miché", "short" => "Mi."],
        "34"=>["name" => "Nahum", "short" => "Na."],
        "35"=>["name" => "Habakuk", "short" => "Ha."],
        "36"=>["name" => "Sophonie", "short" => "So."],
        "37"=>["name" => "Aggée", "short" => "Ag."],
        "38"=>["name" => "Zacharie", "short" => "Za."],
        "39"=>["name" => "Malachie", "short" => "Ma."],

        "40"=>["name" => "Matthieu", "short" => "Mt."],
        "41"=>["name" => "Marc", "short" => "Mc."],
        "42"=>["name" => "Luc", "short" => "Lc."],
        "43"=>["name" => "Jean", "short" => "Jn."],
        "44"=>["name" => "Actes des Apôtres", "short" => "Ac."],
        "45"=>["name" => "Romains", "short" => "Rm."],
        "46"=>["name" => "1 Corinthiens", "short" => "1Co."],
        "47"=>["name" => "2 Corinthiens", "short" => "2Co."],
        "48"=>["name" => "Galates", "short" => "Gl."],
        "49"=>["name" => "Éphésiens", "short" => "Ep."],
        "50"=>["name" => "Philippiens", "short" => "Ph."],
        "51"=>["name" => "Colossiens", "short" => "Col."],
        "52"=>["name" => "1 Thessaloniciens", "short" => "1Th."],
        "53"=>["name" => "2 Thessaloniciens", "short" => "2Th."],
        "54"=>["name" => "1 Timothée", "short" => "1Tm."],
        "55"=>["name" => "2 Timothée", "short" => "2Tm."],
        "56"=>["name" => "Tite", "short" => "Tt."],
        "57"=>["name" => "Philémon", "short" => "Phm."],
        "58"=>["name" => "Hebrews", "short" => "He."],
        "59"=>["name" => "Jaques", "short" => "Jc."],
        "60"=>["name" => "1 Pierre", "short" => "1Pe."],
        "61"=>["name" => "2 Pierre", "short" => "2Pe."],
        "62"=>["name" => "1 Jean", "short" => "1Jn."],
        "63"=>["name" => "2 Jean", "short" => "2Jn."],
        "64"=>["name" => "3 Jean", "short" => "3Jn."],
        "65"=>["name" => "Jude", "short" => "Ju."],
        "66"=>["name" => "Apocalypse", "short" => "Ap."]
    );

    private static $germanShorts = array(
        "1. Mose"=>"Gen.", 
        "2. Mose"=>"Ex.", 
        "3. Mose"=>"Lev.",
        "4. Mose"=>"Num.",
        "5. Mose"=>"Dtn.",
        "Josua"=>"Jos.",
        "Richter"=>"Ri.",
        "Rut"=>"Rut",
        "1. Samuel"=>"1Sam.",
        "2. Samuel"=>"2Sam.",
        "1. Könige"=>"1Kön",
        "2. Könige"=>"2Kön",
        "1. Chronik"=>"1Chr.",
        "2. Chronik"=>"2Chr.",
        "Esra"=>"Esra",
        "Nehemia"=>"Neh.",
        "Ester"=>"Est.",
        "Hiob"=>"Ijob",
        "Psalm"=>"Ps.",
        "Sprüche"=>"Spr.",
        "Hohes Lied"=>"Hld.",
        "Prediger"=>"Prd.",
        "Jesaja"=>"Jes.",
        "Jeremia"=>"Jer.",
        "Klagelieder"=>"Klgl.",
        "Hesekiel"=>"Ez.",
        "Daniel"=>"Dan.",
        "Hosea"=>"Hos.",
        "Joel"=>"Joel",
        "Amos"=>"Am.",
        "Obadja"=>"Obd.",
        "Jona"=>"Jona",
        "Micha"=>"Mic.",
        "Nahum"=>"Nah.",
        "Habakuk"=>"Hab.",
        "Zefanja"=>"Zef.",
        "Haggai"=>"Hag.",
        "Sacharja"=>"Sach.",
        "Maleachi"=>"Mal.",

        "Matthäus"=>"Mt.",
        "Markus"=>"Mk.",
        "Lukas"=>"Lk.",
        "Johannes"=>"Joh.",
        "Apostelgeschichte"=>"Apg.",
        "Römer"=>"Rom.",
        "1. Korinther"=>"1Kor.",
        "2. Korinther"=>"2Kor.",
        "Galater"=>"Gal.",
        "Epheser"=>"Eph.",
        "Philipper"=>"Phil.",
        "Kolosser"=>"Kol.",
        "1. Thessalonicher"=>"1Thess.",
        "2. Thessalonicher"=>"2Thess.",
        "1. Timotheus"=>"1Tim.",
        "2. Timotheus"=>"2Tim.",
        "Titus"=>"Tit.",
        "Philemon"=>"Phlm.",
        "Hebräer"=>"Hebr.",
        "Jakobus"=>"Jak.",
        "1. Petrus"=>"1Petr.",
        "2. Petrus"=>"2Petr.",
        "1. Johannes"=>"1Joh.",
        "2. Johannes"=>"2Joh.",
        "3. Johannes"=>"3Joh.",
        "Judas"=>"Jud.",
        "Offenbarung"=>"Offd.",
    );

    static function getShortMap($language)
    {
        if ($language == "Englich") {
            return self::$englichShorts;
        } 
        if ($language == "Deutsch") {
            return self::$germanShorts;
        }
        if ($language == "Francais") {
            return self::$frenchShorts;
        }
    }
}