<?php

namespace App\Utils;

class BibleBookShortUtils {

    private static $englichShorts = array(
        "1"=>["name" => "Genesis", "short" => "Gen."], 
        "2"=>["name" => "Exodus", "short" => "Ex."], 
        "3"=>["name" => "Leviticus", "short" => "Lev."],
        "4"=>["name" => "Numbers", "short" => "Num."],
        "5"=>["name" => "Deuteronomy", "short" => "Deut."],
        "6"=>["name" => "Joshua", "short" => "Josh."],
        "7"=>["name" => "Judges", "short" => "Judg."],
        "8"=>["name" => "Ruth", "short" => "Ruth"],
        "9"=>["name" => "1 Samuel", "short" => "1Sam."],
        "10"=>["name" => "2 Samuel", "short" => "2Sam."],
        "11"=>["name" => "1 Kings", "short" => "1Kings"],
        "12"=>["name" => "2 Kings", "short" => "2Kings"],
        "13"=>["name" => "1 Chronicles", "short" => "1Chron."],
        "14"=>["name" => "2 Chronicles", "short" => "2Chron."],
        "15"=>["name" => "Ezra", "short" => "Ezra"],
        "16"=>["name" => "Nehemiah", "short" => "Neh."],
        "17"=>["name" => "Esther", "short" => "Est."],
        "18"=>["name" => "Job", "short" => "Job"],
        "19"=>["name" => "Psalms", "short" => "Ps."],
        "20"=>["name" => "Proverbs", "short" => "Prov."],
        "21"=>["name" => "Ecclesiastes", "short" => "Eccles."],
        "22"=>["name" => "Song of Songs", "short" => "Song"],
        "23"=>["name" => "Isaiah", "short" => "Isa."],
        "24"=>["name" => "Jeremiah", "short" => "Jer."],
        "25"=>["name" => "Lamentations", "short" => "Lam."],
        "26"=>["name" => "Ezekiel", "short" => "Ezek."],
        "27"=>["name" => "Daniel", "short" => "Dan."],
        "28"=>["name" => "Hosea", "short" => "Hos."],
        "29"=>["name" => "Joel", "short" => "Joel"],
        "30"=>["name" => "Amos", "short" => "Amos"],
        "31"=>["name" => "Obadiah", "short" => "Obad."],
        "32"=>["name" => "Jonah", "short" => "Jonah"],
        "33"=>["name" => "Micah", "short" => "Mic."],
        "34"=>["name" => "Nahum", "short" => "Nah."],
        "35"=>["name" => "Habakkuk", "short" => "Hab."],
        "36"=>["name" => "Zephaniah", "short" => "Zeph."],
        "37"=>["name" => "Haggai", "short" => "Hag."],
        "38"=>["name" => "Zechariah", "short" => "Zech."],
        "39"=>["name" => "Malachi", "short" => "Mal."],

        "40"=>["name" => "Matthew", "short" => "Matt."],
        "41"=>["name" => "Mark", "short" => "Mark"],
        "42"=>["name" => "Luke", "short" => "Luke"],
        "43"=>["name" => "John", "short" => "John"],
        "44"=>["name" => "Acts", "short" => "Acts"],
        "45"=>["name" => "Romans", "short" => "Rom."],
        "46"=>["name" => "1 Corinthians", "short" => "1Cor."],
        "47"=>["name" => "2 Corinthians", "short" => "2Cor."],
        "48"=>["name" => "Galatians", "short" => "Gal."],
        "49"=>["name" => "Ephesians", "short" => "Eph."],
        "50"=>["name" => "Philippians", "short" => "Phil."],
        "51"=>["name" => "Colossians", "short" => "Col."],
        "52"=>["name" => "1 Thessalonians", "short" => "1Thess."],
        "53"=>["name" => "2 Thessalonians", "short" => "2Thess."],
        "54"=>["name" => "1 Timothy", "short" => "1Tim."],
        "55"=>["name" => "2 Timothy", "short" => "2Tim."],
        "56"=>["name" => "Titus", "short" => "Titus"],
        "57"=>["name" => "Philemon", "short" => "Philem."],
        "58"=>["name" => "Hebrews", "short" => "Heb."],
        "59"=>["name" => "James", "short" => "James"],
        "60"=>["name" => "1 Peter", "short" => "1Pet."],
        "61"=>["name" => "2 Peter", "short" => "2Pet."],
        "62"=>["name" => "1 John", "short" => "1Joh."],
        "63"=>["name" => "2 John", "short" => "2Joh."],
        "64"=>["name" => "3 John", "short" => "3Joh."],
        "65"=>["name" => "Jude", "short" => "Jude"],
        "66"=>["name" => "Revelation", "short" => "Rev."]
    );

    private static $frenchShorts = array(
        "1"=>["name" => "Genèse", "short" => "Gn."], 
        "2"=>["name" => "Exode", "short" => "Ex."],  
        "3"=>["name" => "Lévitique", "short" => "Lv."],
        "4"=>["name" => "Nombres", "short" => "Nb."],
        "5"=>["name" => "Deutéronome", "short" => "Dt."],
        "6"=>["name" => "Josué", "short" => "Js."],
        "7"=>["name" => "Juges", "short" => "Jg."],
        "8"=>["name" => "Ruth", "short" => "Rt."],
        "9"=>["name" => "1 Samuel", "short" => "1Sam."],
        "10"=>["name" => "2 Samuel", "short" => "2Sam."],
        "11"=>["name" => "1 Rois", "short" => "1Ro"],
        "12"=>["name" => "2 Rois", "short" => "2Ro"],
        "13"=>["name" => "1 Chroniques", "short" => "1Ch."],
        "14"=>["name" => "2 Chroniques", "short" => "2Ch."],
        "15"=>["name" => "Esdras", "short" => "Esd."],
        "16"=>["name" => "Néhémie", "short" => "Ne."],
        "17"=>["name" => "Esther", "short" => "Est."],
        "18"=>["name" => "Job", "short" => "Jb."],
        "19"=>["name" => "Psalms", "short" => "Ps."],
        "20"=>["name" => "Proverbes", "short" => "Pr."],
        "21"=>["name" => "Ecclésiastes", "short" => "Ec."],
        "22"=>["name" => "Cantique", "short" => "Cant."],
        "23"=>["name" => "Ésaïe", "short" => "Es."],
        "24"=>["name" => "Jérémie", "short" => "Jer."],
        "25"=>["name" => "Lamentations", "short" => "Lam."],
        "26"=>["name" => "Ézékiel", "short" => "Ezek."],
        "27"=>["name" => "Daniel", "short" => "Dan."],
        "28"=>["name" => "Osée", "short" => "Hos."],
        "29"=>["name" => "Joël", "short" => "Jl."],
        "30"=>["name" => "Amos", "short" => "Am."],
        "31"=>["name" => "Abdias", "short" => "Ab."],
        "32"=>["name" => "Jonas", "short" => "Jon."],
        "33"=>["name" => "Miché", "short" => "Mi."],
        "34"=>["name" => "Nahum", "short" => "Na."],
        "35"=>["name" => "Habakuk", "short" => "Ha."],
        "36"=>["name" => "Sophonie", "short" => "So."],
        "37"=>["name" => "Aggée", "short" => "Ag."],
        "38"=>["name" => "Zacharie", "short" => "Za."],
        "39"=>["name" => "Malachie", "short" => "Ma."],

        "40"=>["name" => "Matthieu", "short" => "Mt."],
        "41"=>["name" => "Marc", "short" => "Mc."],
        "42"=>["name" => "Luc", "short" => "Lc."],
        "43"=>["name" => "Jean", "short" => "Jn."],
        "44"=>["name" => "Actes des Apôtres", "short" => "Ac."],
        "45"=>["name" => "Romains", "short" => "Rm."],
        "46"=>["name" => "1 Corinthiens", "short" => "1Co."],
        "47"=>["name" => "2 Corinthiens", "short" => "2Co."],
        "48"=>["name" => "Galates", "short" => "Gl."],
        "49"=>["name" => "Éphésiens", "short" => "Ep."],
        "50"=>["name" => "Philippiens", "short" => "Ph."],
        "51"=>["name" => "Colossiens", "short" => "Col."],
        "52"=>["name" => "1 Thessaloniciens", "short" => "1Th."],
        "53"=>["name" => "2 Thessaloniciens", "short" => "2Th."],
        "54"=>["name" => "1 Timothée", "short" => "1Tm."],
        "55"=>["name" => "2 Timothée", "short" => "2Tm."],
        "56"=>["name" => "Tite", "short" => "Tt."],
        "57"=>["name" => "Philémon", "short" => "Phm."],
        "58"=>["name" => "Hebrews", "short" => "He."],
        "59"=>["name" => "Jaques", "short" => "Jc."],
        "60"=>["name" => "1 Pierre", "short" => "1Pe."],
        "61"=>["name" => "2 Pierre", "short" => "2Pe."],
        "62"=>["name" => "1 Jean", "short" => "1Jn."],
        "63"=>["name" => "2 Jean", "short" => "2Jn."],
        "64"=>["name" => "3 Jean", "short" => "3Jn."],
        "65"=>["name" => "Jude", "short" => "Ju."],
        "66"=>["name" => "Apocalypse", "short" => "Ap."]
    );

    private static $germanShorts = array(
        "1"=>["name" => "1. Mose", "short" => "Gen."], 
        "2"=>["name" => "2. Mose", "short" => "Ex."], 
        "3"=>["name" => "3. Mose", "short" => "Lev."],
        "4"=>["name" => "4. Mose", "short" => "Num."],
        "5"=>["name" => "5. Mose", "short" => "Dtn."],
        "6"=>["name" => "Josua", "short" => "Jos."],
        "7"=>["name" => "Richter", "short" => "Ri."],
        "8"=>["name" => "Rut", "short" => "Rut"],
        "9"=>["name" => "1. Samuel", "short" => "1Sam."],
        "10"=>["name" => "2. Samuel", "short" => "2Sam."],
        "11"=>["name" => "1. Könige", "short" => "1Kön"],
        "12"=>["name" => "2. Könige", "short" => "2Kön"],
        "13"=>["name" => "1. Chronik", "short" => "1Chr."],
        "14"=>["name" => "2. Chronik", "short" => "2Chr."],
        "15"=>["name" => "Esra", "short" => "Esra"],
        "16"=>["name" => "Nehemia", "short" => "Neh."],
        "17"=>["name" => "Ester", "short" => "Est."],
        "18"=>["name" => "Hiob", "short" => "Ijob"],
        "19"=>["name" => "Psalm", "short" => "Ps."],
        "20"=>["name" => "Sprüche", "short" => "Spr."],
        "21"=>["name" => "Hohes Lied", "short" => "Hld."],
        "22"=>["name" => "Prediger", "short" => "Prd."],
        "23"=>["name" => "Jesaja", "short" => "Jes."],
        "24"=>["name" => "Jeremia", "short" => "Jer."],
        "25"=>["name" => "Klagelieder", "short" => "Klgl."],
        "26"=>["name" => "Hesekiel", "short" => "Ez."],
        "27"=>["name" => "Daniel", "short" => "Dan."],
        "28"=>["name" => "Hosea", "short" => "Hos."],
        "29"=>["name" => "Joel", "short" => "Joel"],
        "30"=>["name" => "Amos", "short" => "Am."],
        "31"=>["name" => "Obadja", "short" => "Obd."],
        "32"=>["name" => "Jona", "short" => "Jona"],
        "33"=>["name" => "Micha", "short" => "Mic."],
        "34"=>["name" => "Nahum", "short" => "Nah."],
        "35"=>["name" => "Habakuk", "short" => "Hab."],
        "36"=>["name" => "Zefanja", "short" => "Zef."],
        "37"=>["name" => "Haggai", "short" => "Hag."],
        "38"=>["name" => "Sacharja", "short" => "Sach."],
        "39"=>["name" => "Maleachi", "short" => "Mal."],

        "40"=>["name" => "Matthäus", "short" => "Mt."],
        "41"=>["name" => "Markus", "short" => "Mk."],
        "42"=>["name" => "Lukas", "short" => "Lk."],
        "43"=>["name" => "Johannes", "short" => "Joh."],
        "44"=>["name" => "Apostelgeschichte", "short" => "Apg."],
        "45"=>["name" => "Römer", "short" => "Rom."],
        "46"=>["name" => "1. Korinther", "short" => "1Kor."],
        "47"=>["name" => "2. Korinther", "short" => "2Kor."],
        "48"=>["name" => "Galater", "short" => "Gal."],
        "49"=>["name" => "Epheser", "short" => "Eph."],
        "50"=>["name" => "Philipper", "short" => "Phil."],
        "51"=>["name" => "Kolosser", "short" => "Kol."],
        "52"=>["name" => "1. Thessalonicher", "short" => "1Thess."],
        "53"=>["name" => "2. Thessalonicher", "short" => "2Thess."],
        "54"=>["name" => "1. Timotheus", "short" => "1Tim."],
        "55"=>["name" => "2. Timotheus", "short" => "2Tim."],
        "56"=>["name" => "Titus", "short" => "Tit."],
        "57"=>["name" => "Philemon", "short" => "Phlm."],
        "58"=>["name" => "Hebräer", "short" => "Hebr."],
        "59"=>["name" => "Jakobus", "short" => "Jak."],
        "60"=>["name" => "1. Petrus", "short" => "1Petr."],
        "61"=>["name" => "2. Petrus", "short" => "2Petr."],
        "62"=>["name" => "1. Johannes", "short" => "1Joh."],
        "63"=>["name" => "2. Johannes", "short" => "2Joh."],
        "64"=>["name" => "3. Johannes", "short" => "3Joh."],
        "65"=>["name" => "Judas", "short" => "Jud."],
        "66"=>["name" => "Offenbarung", "short" => "Offd."]
    );

    static function getShortMap($language)
    {
        if ($language == "Englich") {
            return self::$englichShorts;
        } 
        if ($language == "Deutsch") {
            return self::$germanShorts;
        }
        if ($language == "Francais") {
            return self::$frenchShorts;
        }
    }
}